### ISSUE TITLE
Resource cannot be found error

### ISSUE THREAD

**Issue by GauravDhavale** [stephaneey/transparent-auth-bot#1]
Hi Stephan, 

I'm facing issues while running this application. Getting following error:
After running the application from visual studio or directly using the URL of published App, I get the error as 
Server Error in '/' Application. 
The resource cannot be found. 
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 
 Requested URL: /
-------------------------------------------------
The steps I have implemented to run the application are:
1: Created a Web App on Azure portal on my free subscription with admin account
2: Created an Azure AD App of type Web and gave the sign in URL as the URL of my web app from step 1, created a key for this app. Capture Application ID. Selected read directory, read all basic profiles, read all groups delegated permissions.
3:  Register a Bot, capture Microsoft App ID, password and Web Chat channel Secret. Updated endpoint as https://mybotname.azurewebsites.net/messages/api
mybotname value is different.
Selected similar Microsoft Graph Permissions in application registration portal 
4: Downloaded your Github project, updated following parameter in web.config
Botid: Bot handle given during Bot registration
BotSecret: Web channel secret
MicrosoftAppId and MicrosoftAppPassword  values captured during 3rd step
ClientId: Application ID captured during Azure AD application registration
ClientSecret: value obtained during step 2
Domain: value found in domain names in Azure AD
TenantId: Directory ID Value from Azure AD under properties 
Replaced RedirectUri and PostLogoutRedirectUri app name with my web app name
5: Published the application from the visual studio in web app created in 1st step. 
6: Run the application

Can you please tell me if I'm missing any step?
 I have azure trail subscription with my personal account.

**Comment by stephaneey** [comment]
Hello,

It might be a typo of yours but we never know, you mentioned:

https://mybotname.azurewebsites.net/messages/api

but the url should be

https://mybotname.azurewebsites.net/api/messages

Also make sure you registered the right URL endpoint during the bot registration

Best Regards

**Comment by GauravDhavale** [comment]
Hi,
Thanks, that was a typo. 
My application asks me to sign 
I have a question regarding the two connection strings in Web.config. Do I need to create a Web App with SQL in Azure and then create an AuthenticationDB database in it? 

Thanks
